### ISSUE TITLE
Disable.ifSynthetic issue

### ISSUE THREAD

**Issue by eed3si9n** [scalacenter/sbt-scalafix#4]
### Steps

```
rules = [
  Disable
]

Disable.ifSynthetic = [
  "scala.Predef.any2stringadd"
]
```

#### Main.scala

```scala
object Main {
  def main(args: Array[String]): Unit = {
    println(List(1) + "any2stringadd")
  }
}
```

Run `scalafixCli` from sbt shell.

### Problem

This does not catch the any2stringadd.

### Expectation

It results in an error.

### Notes

Note that this particular test is the same test tested in https://github.com/scalacenter/scalafix/blob/v0.6.0-M12/scalafix-tests/input/src/main/scala/test/DisableSimple.scala, it might be a separate issue from  https://github.com/scalacenter/scalafix/issues/650.

**Comment by olafurpg** [comment]
Thanks for reporting! This issue should be reported in scalacenter/scalafix since this repo is dedicated for the sbt plugin only. The solution is to add `scalacOptions += "-P:semanticdb:synthetics:on"` as the scalafix build does here https://github.com/scalacenter/scalafix/blob/a59dee66da747966eab318dd69e73bebb6fd0d76/project/ScalafixBuild.scala#L72 This requirement is not documented on the website since `Disable.ifSynthetic` was introduced in a recent v0.6 milestone release and the website only document the stable v0.5 release.

I opened https://github.com/scalacenter/scalafix/issues/780 to track documenting the scalac option requirement.

**Comment by eed3si9n** [comment]
I see. Thanks for the explanation!

**Comment by olafurpg** [comment]
I btw recommend to wait until v0.6 stable is out or stay on v0.5. There have been a lot of changes in the current milestone that are intentionally undocumented since I prefer to document breaking change once I know they're final
